name: jwt-assignment
services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - app_data:/app/data
    restart: always

volumes:
  app_data:
